### ISSUE TITLE
Including Loader.js and Dialog.js on the same page causes a namespace collision

### ISSUE THREAD

**Issue by andersborum** [bukacekd/loader#1]
First of all, thanks for taking the time to share these stand alone libraries, they're easy to work with a comes with some nifty features.

However, I'm running into an issue when including both the `Loader.js` and `Dialog.js` on the same page, and it appears the libraries can't co-exist because of the shared js4y namespace (the last included library overwrites the definition of the first library). I'm quite certain I'm using the latest versions of the libraries.

The following error is thrown in the console:

`TypeError: js4y.components.Loader is not a constructor`

Here's a small repro, and please note that Loader.js (as used in the script body) is included **before** Dialog.js.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="src/style.css">
    <script src="https://unpkg.com/@js4y/loader/dist/index.js"></script>
    <script src="https://unpkg.com/@js4y/dialog/dist/index.js"></script>
  </head>
  <body>
  <script>
   new js4y.components.Loader(document.body);
  </script>
  </body>
</html>
```

Am I missing something obvious here?

**Comment by bukacekd** [comment]
I have modified the builds of both libraries which should solve this problem. Please try the latest versions of both libraries.

**Comment by andersborum** [comment]
I can confirm that v1.1.1 as released has fixed the issue and the components now co-exist without namespace collisions.
